### PR TITLE
Remove january from dawnsci

### PR DESCRIPTION
**Pull request by gerring**

### CODE REVIEW

**Comment by gerring** [comment]
Looks like the january pom now hard codes some things:
	<parent>
		<relativePath>../releng/org.eclipse.january.releng/pom.xml</relativePath>
		<groupId>org.eclipse.january</groupId>
		<artifactId>org.eclipse.january.releng</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

This is incorrect, it should be:
	<parent>
		<artifactId>org.eclipse.january</artifactId>
		<groupId>org.eclipse</groupId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

**Comment by gerring** [comment]
@jonahkichwacoders and @PeterC-DLS what is the solution to having january in this build? It seems that the pom was made specific to the january build.

**Comment by jonahkichwacoders** [comment]
@gerring I believe the solution is to consume January, not build it from source again.

Adding @mwebber for his opinion, but that was my understanding of how to pull in the deps.

**Comment by gerring** [comment]
Matt does not look after the dawnsci and daq-eclipse, sub-builds, I do. I
need the latest and greatest for my travis builds...

**Comment by jonahkichwacoders** [comment]
Then you want latest p2 site:
http://download.eclipse.org/january/builds/january-master/latest/repository/

It is continuously integrated and published on stable builds.

Jonah

**Comment by gerring** [comment]
That seemed to work but I need to do the same to daq-eclipse

**Pull request merged**
