### PR TITLE
Fixed the RectangularROI bounds() method.

### PR DESCRIPTION
**Pull request by MattTaylorDLS**
http://jira.diamond.ac.uk/browse/DAQ-356
Signed-off-by: Matthew Taylor <matthew.taylor@diamond.ac.uk>

### CODE REVIEW

**Comment by PeterC-DLS** [comment]
Your fix seems to suggest that other ROIs pass bounds which are wrong. Is that the case?

**Comment by MattTaylorDLS** [comment]
It is possible to create a rectangular ROI that is 'backwards' - i.e. it has one of its lenghts as a negative value. See the test 'RectRoiBounds_Nested_NNPNNNPP' in the test class I have just commited (missed from the initial commit). This would fail with the current implementation of bounds().

**Comment by PeterC-DLS** [comment]
I think the better fix is to fix the constructors so that the lengths are always non-negative. (Note the box selection does not allow you to draw out such rectangles.) Either throw IAEs or shift the start point and angle accordingly. And clarify in the Javadocs too.

**Comment by MattTaylorDLS** [comment]
OK, I can do that. It's not just the constructors though, it'll need to be every method that adjusts the lengths, e.g. SetLengts(), addToLengths()

Would you prefer to throw exception or shift the start and angle?

**Comment by MattTaylorDLS** [comment]
I've thrown IAE in constructors and on methods that adjust the length. Updated tests as a result.

**Comment by PeterC-DLS** [comment]
Looks good, thanks.

**Pull request merged**
