### PR TITLE
Update Ant test runners to match what the travis build does

### PR DESCRIPTION
**Pull request by mwebber**

### CODE REVIEW

**Review by PeterC-DLS — COMMENTED** [review]
I'm not sure this commit brings both mechanisms to parity.

Travis sets test.includes to org/eclipse/dawnsci/**/*Suite.java and so it seems to miss some tests...

**Comment by mwebber** [comment]
> Travis sets test.includes to org/eclipse/dawnsci/**/*Suite.java and so it seems to miss some tests...

It should run the correct tests. The current set-up actually runs some tests twice, because ```org.eclipse.dawnsci.analysis.dataset.AllSuite``` actually includes these 3:
```
org.eclipse.dawnsci.analysis.dataset.roi.AllSuite
org.eclipse.dawnsci.analysis.dataset.function.AllSuite
org.eclipse.dawnsci.analysis.dataset.slicer.AllSuite
```
so they (currently) end up being run twice. It's sufficient just to include the top-level parent.
This should be verified (or not) once http://jenkins.diamond.ac.uk:8080/view/Dawn_DEV/job/DawnDiamond.master-junit.tests-gerrit/71/ completes.

**Comment by PeterC-DLS** [comment]
But travis does not run, for example, xdi.test

**Comment by mwebber** [comment]
Closing without merging - change is not correct and not required.

**Pull request closed without merging**
