### PR TITLE
Add cached file for minimal(!) speed-up

### PR DESCRIPTION
**Pull request by PeterC-DLS**

### CODE REVIEW

**Comment by PeterC-DLS** [comment]
That line is only run again if {{isWriteable}} is false. As it is true after first execution, then it is not called again!

**Comment by gerring** [comment]
When I run NexusStepScanSpeedTest.testBareNexusStepScanSpeed() that block is hit every time. Simply put a break point inside it and run the test.

**Comment by PeterC-DLS** [comment]
Because as it is done once per lazy dataset and not on every {{setSlice}} call.

**Comment by gerring** [comment]
clear

**Pull request merged**
