### PR TITLE
Improve MJpeg performance

### PR DESCRIPTION
**Pull request by MattTaylorDLS**
Made the MJpegStreamer use a non blocking implementation.
http://jira.diamond.ac.uk/browse/DAQ-298

Signed-off-by: Matthew Taylor <matthew.taylor@diamond.ac.uk>

### CODE REVIEW

**Comment by gerring** [comment]
Do you want me to close it?

**Comment by MattTaylorDLS** [comment]
This is now working and can be checked and merged in.

**Comment by PeterC-DLS** [comment]
Unfortunately, you will need to update your PR again as the base has changed.

**Comment by gerring** [comment]
ip-validation check can go bad after an update. Soemtimes it is easier to start with a clean up-to-date branch when this happens because one commit message (probably the merge) does not validate with eclipse.

**Comment by MattTaylorDLS** [comment]
Not sure why that test failed. It's nothing to do with the changes I made. Perhaps running the tests again will pass?

**Comment by PeterC-DLS** [comment]
I have restarted the Travis CI build...

**Comment by MattTaylorDLS** [comment]
Thanks peter. Seems to have worked this time

**Pull request merged**
