### PR TITLE
Javafx volume trace axes addition 2

### PR DESCRIPTION
**Pull request by JoelAOgden**
My local copy of the original branch was being a pain and wouldn't let me push.

Rather than spending >5 mins fixing it, I just made a new branch. Easy fix.

### CODE REVIEW

**Comment by JoelAOgden** [comment]
Hurray!

**Comment by JoelAOgden** [comment]
Didn't realise updating the branch would create a non-signed off commit. :disappointed:

**Comment by gerring** [comment]
Nor did I, sorry. Change a comment, add the signed off line and push on to the branch.

**Comment by JoelAOgden** [comment]
Give me a minute, my git repo is broken and keeps merging after every commit, going to amend via the terminal.

**Pull request merged**
