### PR TITLE
SCI-6656: org.eclipse.dawnsci.xdi -> new plugin for reading XDI files

### PR DESCRIPTION
**Pull request by tschoonj**
Signed-off-by: Tom Schoonjans <Tom.Schoonjans@diamond.ac.uk>

@mwebber this will need some Buckminster changes at your end if I am not mistaken?

### CODE REVIEW

**Comment by mwebber** [comment]
Materialize (Buckminster) and build (as part of Dawn) both look good from my point of view.

**Comment by tschoonj** [comment]
@jacobfilik @PeterC-DLS Would you mind merging this one in? Thanks!

**Comment by tschoonj** [comment]
Thanks Pete!

**Comment by tschoonj** [comment]
Hi @bruceravel,

This PR (and my subsequent work [here](https://github.com/DawnScience/scisoft-core/commit/4842a70057c16310bbac85066dde2cc87068c9a7)), ensures that the XDI file format will be supported for reading in the next stable release of DAWN.

I appreciate that you would have preferred a true binding to your C library using Java Native Interface, but this approach was considerably faster to implement as well as far less likely to crash the DAWN JVM :smile: 

Feel free to point your users to this plugin, if you would ever get someone asking for XDI support in Java.

Please note that I only implemented reading support, as we currently have no plans of writing XDI files, whether at acquisition time of during data analysis, but this may change if someone asks for it at Diamond...

Best,

Tom

**Pull request merged**
