### PR TITLE
SCI-5903: add new method getTracesByClass to ITraceSystem

### PR DESCRIPTION
**Pull request by tschoonj**
With default implementation!
Enforces Java 1.8 requirement

### CODE REVIEW

**Comment by tschoonj** [comment]
@PeterC-DLS any thoughts on how I can fix this?

Thanks in advance

**Comment by PeterC-DLS** [comment]
Class path and manifest files need updating too

**Comment by tschoonj** [comment]
Actually I managed to get rid of the Java 8 related error. But other ones have popped up...

Will fix the MANIFEST.MF and buildpath

**Comment by tschoonj** [comment]
Hmmm... seems to be weird january issue:

````
[ERROR] /home/travis/build/eclipse/org.eclipse.dawnsci/org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/dyn/DynamicImage.java:[119]

[ERROR] Serializable buffer = DatasetUtils.cast(greyScale ? ShortDataset.class : RGBDataset.class, sdata).getBuffer();

[ERROR] ^^^^

[ERROR] The method cast(IDataset, int) in the type DatasetUtils is not applicable for the arguments ((greyScale ? ShortDataset.class : RGBDataset.class), IDataset)

[ERROR] /home/travis/build/eclipse/org.eclipse.dawnsci/org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/dyn/DynamicImage.java:[119]

[ERROR] Serializable buffer = DatasetUtils.cast(greyScale ? ShortDataset.class : RGBDataset.class, sdata).getBuffer();

[ERROR] ^^^^^^^^^^^^^^^^^^

[ERROR] Type mismatch: cannot convert from Class<ShortDataset> to IDataset

[ERROR] /home/travis/build/eclipse/org.eclipse.dawnsci/org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/dyn/DynamicImage.java:[119]

[ERROR] Serializable buffer = DatasetUtils.cast(greyScale ? ShortDataset.class : RGBDataset.class, sdata).getBuffer();

[ERROR] ^^^^^^^^^^^^^^^^

[ERROR] Type mismatch: cannot convert from Class<RGBDataset> to IDataset

[ERROR] /home/travis/build/eclipse/org.eclipse.dawnsci/org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/RemoteDataset.java:[158]

[ERROR] client.stop();

[ERROR] ^^^^^^^^^^^^^
````

For some reason it is not finding the new cast method

````java
public static <T extends Dataset> T cast(Class<T> clazz, final IDataset d);
````

and instead tries to use

````java
public static Dataset cast(final IDataset d, final int dtype);
````

**Comment by tschoonj** [comment]
Could you try clearing the Travis-CI cache? Perhaps that will work...

**Comment by PeterC-DLS** [comment]
Target platform issue?

**Comment by PeterC-DLS** [comment]
Replace L119 with:
		Dataset data = greyScale ? DatasetUtils.cast(ShortDataset.class, sdata) : DatasetUtils.cast(RGBDataset.class, sdata);
		Serializable buffer = data.getBuffer();

Also add org.eclipse.jetty.websocket.common as a required bundled

**Comment by tschoonj** [comment]
Thanks Pete, works fine now...

**Pull request merged**
