### PR TITLE
Unit tests for the Outlier class (2)

### PR DESCRIPTION
**Pull request by tcspain**
Unit tests, and the entries in the test suite

### CODE REVIEW

**Comment by gerring** [comment]
Did your test run?

**Comment by tcspain** [comment]
How would I tell?
If I run AllSuite.java as a unit test in eclipse, my tests run, successfully.

**Comment by gerring** [comment]
Search for "T E S T S" in the output, I don't think those tests are being picked up.

**Comment by tcspain** [comment]
In the travis log, the Outlier test output is between lines 1270 to 1285.

**Pull request merged**
