### PR TITLE
Added the need for axes in the volume render trace.

### PR DESCRIPTION
**Pull request by JoelAOgden**
\ue022 <- test

Signed-off-by: Joel Ogden <joel.ogden@diamond.ac.uk>

### CODE REVIEW

**Comment by JoelAOgden** [comment]
:smile_cat: <- I am a happy man

**Comment by JoelAOgden** [comment]
:santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa: :santa:

**Comment by gerring** [comment]
org.eclipse.dawnsci.plotting.examples does not compile:
[ERROR] volume.setData(
[ERROR] ^^^^^^^
[ERROR] The method setData(int[], IDataset, double, double, double[], double[], List<? extends IDataset>) in the type IVolumeRenderTrace is not applicable for the arguments (int[], IDataset, double, double, double[], double[])

This argument list seems to have become massive. Does it all need to be provided on the setData(....) call? For instance setData(some data)   setFred(freds value)   rather than everything in setData(...)

Just a thought!

**Comment by JoelAOgden** [comment]
Yeah, you make a good point, i'll look into decreasing it as much as possible.

**Comment by gerring** [comment]
Just updated branch, that might help

**Comment by gerring** [comment]
Same compile error. Have you not pushed something onto the branch Joel?

**Pull request closed without merging**
